"""followers

Revision ID: 50564edaa64c
Revises: b4c0019768a9
Create Date: 2020-07-07 16:25:11.680561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50564edaa64c'
down_revision = 'b4c0019768a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
